### ISSUE TITLE
Compilation terminated due to mgosh_gcp.h not found

### ISSUE THREAD

**Issue by nitinpandey3004** [alvarowolfx/weather-station-gcp-mongoose-os#1]
/esp8266/build_contexts/build_ctx_226160062/src/main.c:2:22: fatal error: mgos_gcp.h: No such file or directory
[Jan 19 23:43:03.736]  #include "mgos_gcp.h"

[Jan 19 23:43:03.736]                       ^
[Jan 19 23:43:03.736] compilation terminated.

I guess this is due to no include file i.e /include/mgos_gcp.h is absent in mgosh library.

**Comment by alvarowolfx** [comment]
Fixed. There is no need to include mos_gcp.h anymore. Thanks for submitting this issue.

**Comment by nitinpandey3004** [comment]
Thanks for your quick reply but sorry to say that but if I donot include "mogos_gcp.h" I am getting error related to function mgos_gcp_init();


] make: Entering directory '/app'
[Jan 23 10:18:28.358]   CC    /fwbuild-volumes/1.24/apps/my_app/esp8266/build_contexts/build_ctx_829484399/src/main.c -> /fwbuild-volumes/1.24/apps/my_app/esp8266/build_contexts/build_ctx_829484399/build/objs/main.c.o
[Jan 23 10:18:28.358] /fwbuild-volumes/1.24/apps/my_app/esp8266/build_contexts/bui
ld_ctx_829484399/src/main.c: In function 'mgos_app_init':
[Jan 23 10:18:28.358] /fwbuild-volumes/1.24/apps/my_app/esp8266/build_contexts/build_ctx_829484399/src/main.c:6:3: error: implicit declaration of function 'mgos_gcp_init' [-Werror=implicit-function-declaration]
[Jan 23 10:18:28.358]    mgos_gcp_init();

[Jan 23 10:18:28.358]    ^
[Jan 23 10:18:28.358] cc1: all warnings being treated as errors

**Comment by alvarowolfx** [comment]
But I removed the method call to the gcp_init function. The function is called when the library is imported, so there is no need to call it ourself. Did you got the updated code ? I made a build on my computer and it’s all green now.

**Comment by nitinpandey3004** [comment]
Thank u very much all issues are resolved.Thanks for quick support and reply.
