### ISSUE TITLE
command waits for further input

### ISSUE THREAD

**Issue by vishnu-chalil** [alvarowolfx/weather-station-gcp-mongoose-os#3]
Iam new at firebase and GCP.I dont understand why this comma d is not executing.It waits for further input with >

firebase functions:config:set bigquery.datasetname="weather_station_iot" bigquery.tablename="raw_data”

**Comment by alvarowolfx** [comment]
Hmmm, strange this error, is not supposed to wait for further input from the user. If you hit enter again it gives a error ?

**Comment by vishnu-chalil** [comment]
![command_error](https://user-images.githubusercontent.com/23023241/43238990-2c1483e0-90ae-11e8-9163-56c38188e3b6.png)


Upon pressing enter its justs keep giving space for input.Is there something I should enter there

**Comment by vishnu-chalil** [comment]
@alvarowolfx  I tired editing the index.js avoiding the bigquery part.

The code looks like this now

        const functions = require('firebase-functions');
	const admin = require('firebase-admin');

	admin.initializeApp(functions.config().firebase);

	const db = admin.database();

	/**
	 * Receive data from pubsub, then 
	 * Write telemetry raw data to bigquery
	 * Maintain last data on firebase realtime database
	 */
	exports.receiveTelemetry = functions.pubsub
	  .topic('telemetry-topic')
	  .onPublish(event => {
	    const attributes = event.data.attributes;
	    const message = event.data.json;

	    const deviceId = attributes['deviceId'];

	    const data = {
	      humidity: message.hum,
	      temp: message.temp,
	      deviceId: deviceId,
	      timestamp: event.timestamp
	    };

	    if (
	      message.hum < 0 ||
	      message.hum > 100 ||
	      message.temp > 100 ||
	      message.temp < -50
	    ) {
	      // Validate and do nothing
	      return;
	    }

	    return Promise.all([
	      updateCurrentDataFirebase(data)
	    ]);
	  });

	/** 
	 * Maintain last status in firebase
	*/
	function updateCurrentDataFirebase(data) {
	  return db.ref(`/devices/${data.deviceId}`).set({
	    humidity: data.humidity,
	    temp: data.temp,
	    lastTimestamp: data.timestamp
	  });
	}

but now Iam getting  error from firebase


TypeError: Cannot read property 'deviceId' of undefined

        at exports.receiveTelemetry.functions.pubsub.topic.onPublish.event (index.js:19)
        at Object.<anonymous> (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:112)
        at next (native)
        at (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:28)
        at __awaiter (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:24)
        at cloudFunction (/user_code/node_modules/firebase-functions/lib/cloud-functions.js:82)
        at (/var/tmp/worker/worker.js:728)
        at process._tickDomainCallback (next_tick.js:135)

Can u please help

**Comment by didrikr** [comment]
The reason for 'deviceId' not being found is an update to the pubsub API. Pull request #4 fixes it.

**Comment by alvarowolfx** [comment]
You are right @d626, I forgot to update this project with the newest APIs. On other projects I already updated it. I'll accept your PR and update the post to use it. Thanks

**Comment by vishnu-chalil** [comment]
Thanks a lot @alvarowolfx and @d626
